### ISSUE TITLE
列表没有数据header不起作用

### ISSUE THREAD

**Issue by zimengfang** [xinzhazha/RecyclerView#19]

**Comment by xinzhazha** [comment]
先 mAdapter.setheader ，再 recyclerView.setAdapter(mAdapter)

**Comment by zimengfang** [comment]
就是先setheader 再 recyclerView.setAdapter(mAdapter),header不显示

**Comment by xinzhazha** [comment]
贴下代码

**Comment by zimengfang** [comment]
自己代码处理的逻辑,已解决,谢谢
